name: simple_drift
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  drift: ^2.1.0
  path: ^1.8.2
  path_provider: ^2.0.11
  sqlite3_flutter_libs: ^0.5.10
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  drift_dev: ^2.1.0

flutter:
  uses-material-design: true
